server:
  port: 8081

spring:
  application:
    name: auth-service

jwt:
  secret: your_jwt_secret_key_here_make_it_at_least_256_bits
  access-token:
    expiration: 86400000 # 24 hours in milliseconds 